import 'package:flutter/material.dart';

import './question.dart';
import './answer.dart';

class Quiz extends StatelessWidget
{
  final List<Map<String, Object>> questions;
  final VoidCallback _answerQuestion;
  final int _questionIndex;

  Quiz(this.questions, this._answerQuestion, this._questionIndex);

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Question(questions[_questionIndex]['questionText'] as String), //this is the question widget we created in question.dart

      /// the '...' is the spread operator, that gets the elements of
      /// the list and then adds them to the outer list. This ensures we dont have a nested list
      ...(questions[_questionIndex]['answers'] as List<String>)
      /// The map method can be called on a list that performs some operations on
      /// each list item and then returns a new list with the output generated by each item in the original list.
          .map(
              (answer) {
            return Answer(answer, _answerQuestion);
          }).toList()

      /*
          //Old implementation was RaisedButton which got deprecated with flutter version 2
          ElevatedButton(

            //style named argument to change the button graphics
            style: ButtonStyle(
              foregroundColor: MaterialStateProperty.all(Colors.red)
            ),

            onPressed: _answerQuestion, //pointer to a function which will be called when the button is pressed
            child: Text('Option 1'),),

          ElevatedButton(
            style: ButtonStyle(
                foregroundColor: MaterialStateProperty.all(Colors.red),
                backgroundColor: MaterialStateProperty.all(Colors.cyanAccent),
            ),
            onPressed: _answerQuestion,
            child: Text('Option 2'),),

          ElevatedButton(
            onPressed: _answerQuestion,
            child: Text('Option 3'),),
           */

    ]);
  }
}
